//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.30 at 11:14:44 PM CEST 
//
package org.promasi.protocol.messages;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.promasi.game.model.generated.DepartmentModel;
import org.promasi.game.model.generated.EmployeeModel;
import org.promasi.game.model.generated.EmployeeTaskModel;

/**
 * <p>
 * Java class for assignEmployeeTasksRequest complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="assignEmployeeTasksRequest">
 *   &lt;complexContent>
 *     &lt;extension base="{}message">
 *       &lt;sequence>
 *         &lt;element name="employeeId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="tasks" type="{}employeeTaskModel" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "assignEmployeeTasksRequest", propOrder = {
    "employeeId",
    "tasks"
})
public class AssignEmployeeTasksRequest
        extends Message {

    protected String employeeId;
    @XmlElement(required = true)
    protected EmployeeTasks tasks = new EmployeeTasks();

    public AssignEmployeeTasksRequest() {
    }

    public AssignEmployeeTasksRequest(Map<String, List<EmployeeTaskModel> > tasks) {
        for( Map.Entry<String, List<EmployeeTaskModel> > entry : tasks.entrySet() ){
            EmployeeTasks.Entry newEntry = new EmployeeTasks.Entry();
            newEntry.setKey(entry.getKey());
            newEntry.setValue(entry.getValue());
            this.tasks.getEntry().add(newEntry); 
        }
    }

    /**
     * Gets the value of the employeeId property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getEmployeeId() {
        return employeeId;
    }

    /**
     * Sets the value of the employeeId property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setEmployeeId(String value) {
        this.employeeId = value;
    }

    /**
     * Gets the value of the tasks property.
     *
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the tasks property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTasks().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EmployeeTaskModel }
     *
     *
     * @return
     */
    public EmployeeTasks getTasks() {
        if (tasks == null) {
            tasks = new EmployeeTasks();
        }
        return this.tasks;
    }

    public static class EmployeeTasks {

        protected List<AssignEmployeeTasksRequest.EmployeeTasks.Entry> entry;

        /**
         * Gets the value of the entry property.
         *
         * <p>
         * This accessor method returns a reference to the live list, not a
         * snapshot. Therefore any modification you make to the returned list
         * will be present inside the JAXB object. This is why there is not a
         * <CODE>set</CODE> method for the entry property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getEntry().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link DepartmentModel.Employees.Entry }
         *
         *
         * @return
         */
        public List<EmployeeTasks.Entry> getEntry() {
            if (entry == null) {
                entry = new ArrayList<>();
            }
            return this.entry;
        }

        /**
         * <p>
         * Java class for anonymous complex type.
         *
         * <p>
         * The following schema fragment specifies the expected content
         * contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="key" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="value" type="{}employeeModel" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "key",
            "value"
        })
        public static class Entry {

            protected String key;
            protected List<EmployeeTaskModel> value;

            /**
             * Gets the value of the key property.
             *
             * @return possible object is {@link String }
             *
             */
            public String getKey() {
                return key;
            }

            /**
             * Sets the value of the key property.
             *
             * @param value allowed object is {@link String }
             *
             */
            public void setKey(String value) {
                this.key = value;
            }

            /**
             * Gets the value of the value property.
             *
             * @return possible object is {@link EmployeeModel }
             *
             */
            public List<EmployeeTaskModel> getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             *
             * @param value allowed object is {@link EmployeeModel }
             *
             */
            public void setValue(List<EmployeeTaskModel> value) {
                this.value = value;
            }

        }

    }
}
    
