//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.30 at 11:14:44 PM CEST 
//
package org.promasi.protocol.messages;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.promasi.protocol.client.Protocol;

/**
 * <p>
 * Java class for createGameResponse complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="createGameResponse">
 *   &lt;complexContent>
 *     &lt;extension base="{}message">
 *       &lt;sequence>
 *         &lt;element name="gameDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="gameId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="players" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "createGameResponse", propOrder = {
    "gameDescription",
    "gameId",
    "players"
})
public class CreateGameResponse
        extends Message {

    protected String gameDescription;
    protected String gameId;
    @XmlElement(nillable = true)
    protected List<String> players;

    public CreateGameResponse() {
    }

    public CreateGameResponse(String gameId, String gameDescription, List<String> gamePlayers) {
        this.players = gamePlayers;
        this.gameDescription = gameDescription;
        this.gameId = gameId;
    }

    @Override
    public Message dispatch(Protocol protocol) {
        return protocol.dispatch(this);
    }

    /**
     * Gets the value of the gameDescription property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getGameDescription() {
        return gameDescription;
    }

    /**
     * Sets the value of the gameDescription property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setGameDescription(String value) {
        this.gameDescription = value;
    }

    /**
     * Gets the value of the gameId property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getGameId() {
        return gameId;
    }

    /**
     * Sets the value of the gameId property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setGameId(String value) {
        this.gameId = value;
    }

    /**
     * Gets the value of the players property.
     *
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the players property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPlayers().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list {@link String }
     *
     *
     */
    public List<String> getPlayers() {
        if (players == null) {
            players = new ArrayList<String>();
        }
        return this.players;
    }

}
