//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.30 at 11:14:44 PM CEST 
//
package org.promasi.protocol.messages;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.promasi.game.model.generated.GameModelModel;
import org.promasi.protocol.client.Protocol;

/**
 * <p>
 * Java class for createGameRequest complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="createGameRequest">
 *   &lt;complexContent>
 *     &lt;extension base="{}message">
 *       &lt;sequence>
 *         &lt;element name="gameId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="gameModel" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{}companyModel"/>
 *                   &lt;element name="gameDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="gameName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element ref="{}marketPlaceModel"/>
 *                   &lt;element ref="{}projectModel" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "createGameRequest", propOrder = {
    "gameId",
    "gameModel"
})
public class CreateGameRequest
        extends Message {

    protected String gameId;
    protected GameModelModel gameModel;

    public CreateGameRequest() {
    }

    public CreateGameRequest(String gameId, GameModelModel gameModel) {
        this.gameId = gameId;
        this.gameModel = gameModel;
    }

    @Override
    public Message dispatch(Protocol protocol) {
        return protocol.dispatch(this);
    }

    /**
     * Gets the value of the gameId property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getGameId() {
        return gameId;
    }

    /**
     * Sets the value of the gameId property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setGameId(String value) {
        this.gameId = value;
    }

    /**
     * Gets the value of the gameModel property.
     *
     * @return possible object is {@link CreateGameRequest.GameModel }
     *
     */
    public GameModelModel getGameModel() {
        return gameModel;
    }

    /**
     * Sets the value of the gameModel property.
     *
     * @param value allowed object is {@link CreateGameRequest.GameModel }
     *
     */
    public void setGameModel(GameModelModel value) {
        this.gameModel = value;
    }
}
